import Head from "next/head";
import React, { useState } from "react";
import Router from "next/router";

export default function Home() {
  if (
    typeof window !== "undefined" &&
    localStorage.getItem("username") &&
    localStorage.getItem("password")
  ) {
    Router.push("/home");
  }

  const [username, setUsername] = useState(
    (typeof window !== "undefined" && localStorage.username) || ""
  );

  const [password, setPassword] = useState(
    (typeof window !== "undefined" && localStorage.password) || ""
  );

  const handleSubmit = (e) => {
    e.preventDefault();
    localStorage.setItem("username", username);
    localStorage.setItem("password", password);
    Router.push("/home");
  };

  return (
    <>
      <Head>
        <title>Frontend Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Login Page */}
      <div className="flex h-screen justify-center items-center">
        <form
          onSubmit={handleSubmit}
          className="bg-white p-6 rounded-lg shadow-xl"
        >
          <h2 className="text-lg font-medium mb-4">Login</h2>

          {/* input for username  */}
          <div className="mb-4">
            <label
              className="block text-gray-700 font-medium mb-2"
              htmlFor="username"
            >
              Username
            </label>
            <input
              type="text"
              id="username"
              className="w-full border border-gray-400 p-2 rounded-lg"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              required
            />
          </div>

          {/* input for password  */}
          <div className="mb-4">
            <label
              className="block text-gray-700 font-medium mb-2"
              htmlFor="password"
            >
              Password
            </label>
            <input
              type="password"
              id="password"
              className="w-full border border-gray-400 p-2 rounded-lg"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
            />
          </div>

          {/* submit button  */}
          <button
            type="submit"
            className="bg-indigo-500 text-white py-2 px-4 rounded-lg hover:bg-indigo-600"
          >
            Submit
          </button>
        </form>
      </div>
    </>
  );
}
